---
title: "Responsible LLMs"
author: "Dr. Michael Mullarkey"
format:
  revealjs:
    incremental: true
    theme: blood
    transition: fade
    background-transition: fade
    transition-speed: slow
    chalkboard:
      chalk-effect: 0.25
      boardmarker-width: 5
---

# {background-image="https://images.pexels.com/photos/5039250/pexels-photo-5039250.jpeg"}

# A Sleep Deprived Grad Student {background-image="https://images.pexels.com/photos/5039250/pexels-photo-5039250.jpeg" background-opacity="0.7"}

```{css}
.center h1 {
  text-align: center;
}
```

# More Inclusive {background-image="https://images.pexels.com/photos/5039250/pexels-photo-5039250.jpeg" background-opacity="0.5"}

# A Package!

::: {style="text-align: center; margin-top: 1em"}
[gendercoder](https://docs.ropensci.org/gendercoder/){preview-link="true" style="text-align: center"}
:::

# {background-image="https://images.pexels.com/photos/769525/pexels-photo-769525.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"}

# Years Out of Date {background-image="https://images.pexels.com/photos/769525/pexels-photo-769525.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" background-opacity="0.7"}

# Lots of Cases

# {background-image="https://images.pexels.com/photos/4219101/pexels-photo-4219101.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}

# Raw {background-image="https://images.pexels.com/photos/4219101/pexels-photo-4219101.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" background-opacity="0.7"}

# {background-image="https://images.pexels.com/photos/6310231/pexels-photo-6310231.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}

# Structured {background-image="https://images.pexels.com/photos/6310231/pexels-photo-6310231.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" background-opacity="0.7"}

# A Tool?

# Responsible LLMs

# Agenda

- What are LLMs?
- How do LLMs work?
- What are LLMs good at?
- What I've used LLMs for
- What I wouldn't use LLMs for
- Potential roadmap
- Q&A

# What are LLMs?

# {background-image="https://images.pexels.com/photos/3155367/pexels-photo-3155367.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}

# Magic {background-image="https://images.pexels.com/photos/3155367/pexels-photo-3155367.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" background-opacity="0.7"}

# {background-image="https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}

# Scary Magic {background-image="https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" background-opacity="0.7"}

# It's Much Worse

# It's Math {background-image="https://images.pexels.com/photos/374918/pexels-photo-374918.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" background-opacity="0.7"}

# Don't Run Away

# How Do LLMs Work?

# Take in Numbers

# Do Matrix Math

# Spit Out Numbers

# Lots of Non-Numbers?

# {background-image="https://images.pexels.com/photos/1097491/pexels-photo-1097491.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}

# We See {background-image="https://images.pexels.com/photos/1097491/pexels-photo-1097491.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" background-opacity="0.7"}

# {background-image="images/llm_vision.png"}

# LLMs Process {background-image="images/llm_vision.png" background-opacity="0.7"}

# {background-image="images/human_read.png"}

# We Read {background-image="images/human_read.png" background-opacity="0.7"}

# {background-image="images/llm_process_text.png"}

# LLMs Process {background-image="images/llm_process_text.png" background-opacity="0.7"}

# Always Numbers

# Need to Translate

# Example

# Local LLM

::: {style="text-align: center; margin-top: 1em"}
[LLAMA.CPP GITHUB REPO HERE](https://github.com/ggerganov/llama.cpp){preview-link="false" style="text-align: center"}
:::

# {background-image="images/llm_prompt.png" background-size="contain" background-repeat="no-repeat"}

# Tokenizer Converts Words to Numbers

# Tokens

# Matrix Math

# Predicts Next Most Likely Token 

# Tokenizer Converts Tokens to Words

# Tokenizer Converts Numbers to Words

# {background-image="images/llm_response.png" background-size="contain" background-repeat="no-repeat"}

# Always Numbers

# No Magic

# What are LLMs Good At?

# We Don't Know

# Best Guesses

# {background-image="https://images.pexels.com/photos/4219101/pexels-photo-4219101.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}

# Raw {background-image="https://images.pexels.com/photos/4219101/pexels-photo-4219101.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" background-opacity="0.7"}

# {background-image="https://images.pexels.com/photos/6310231/pexels-photo-6310231.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}

# Structured {background-image="https://images.pexels.com/photos/6310231/pexels-photo-6310231.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" background-opacity="0.7"}

# Expansive

# Compressed

# Practically

# Summaries

# WHat I've Used LLMs For

# What They're Good At

# {background-image="images/aiberry_process.png" background-size="contain" background-repeat="no-repeat"}

# {background-image="images/aiberry_summary.png" background-size="contain" background-repeat="no-repeat"}

# {background-image="images/aiberry_scoring.png" background-size="contain" background-repeat="no-repeat"}

# People Prefer Botberry vs. Form

# Read More Here

::: {style="text-align: center; margin-top: 1em"}
[PEER-REVIEWED CLINICAL VALIDATION PAPER](https://osf.io/preprints/psyarxiv/btz6n){preview-link="false" style="text-align: center"}
:::

# What I Wouldn't Use LLMs For

# "Therapist" Chatbots

# 

::: {style="text-align: center; margin-top: 1em"}
["Spicy autocorrect" - Dr. Rumman Chowdhury](www.rollingstone.com%2Fculture%2Fculture-features%2Fwomen-warnings-ai-danger-risk-before-chatgpt-1234804367%2F){preview-link="false" style="text-align: center"}
:::

# Stochastic Parrots

::: {style="text-align: center; margin-top: 1em"}
[PAPER HERE](https://dl.acm.org/doi/pdf/10.1145/3442188.3445922){preview-link="false" style="text-align: center"}
:::

# 

::: {style="text-align: center; margin-top: 1em"}
["You’re a matrix of numbers, you do not have opinions! This is not OK." - Simon Willison](https://simonwillison.net/2023/Aug/27/wordcamp-llms/#personal-ai-ethics){preview-link="true" style="text-align: center"}
:::

# Assessment Chat Bots

# Botberry's Script Isn't from LLMs

# Anything Without Bias Testing

# Bias Testing is Crucial

::: {style="text-align: center; margin-top: 1em"}
[PEER-REVIEWED CLINICAL VALIDATION PAPER](https://osf.io/preprints/psyarxiv/btz6n){preview-link="false" style="text-align: center"}
:::

# Also Crucial for Other Models

# Potential Roadmap

# Humility

# Prioritize Present Harms

# Play to LLM Strengths

# Build Guardrails

# Start Small

# Resources

- [Practical deep learning for coders](https://course.fast.ai/){preview-link="true" style="text-align: center"}
- [Stochastic parrots paper](https://dl.acm.org/doi/pdf/10.1145/3442188.3445922){preview-link="false" style="text-align: center"}
- [Let's build GPT: from scratch, in code, spelled out.](https://www.youtube.com/watch?v=kCc8FmEb1nY&t=1s){preview-link="false" style="text-align: center"}
- [The unseen Black faces of AI algorithms](https://www.nature.com/articles/d41586-022-03050-7){preview-link="false" style="text-align: center"}
- [A hacker's guide to language models](https://www.youtube.com/watch?v=jkrNMKz9pWU){preview-link="false" style="text-align: center"}

# Thanks!

# Q&A

```{r}
#| echo: false

library(palmerpenguins)

```
